- name: Setup Pages
  uses: actions/configure-pages@v3

- name: Upload Files
  uses: actions/upload-pages-artifact@v2
  with:
    path: .

- name: Deploy
  id: deployment
  uses: actions/deploy-pages@v2
